spring:
  application:
    name: Swagger Service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8081

api-docs.endpoints:
  authentication-service:
    gateway-prefix: /api
    service-url: http://service.namespace
    service-path: /resource/api-docs
